version: '3'

services:
  db:
    container_name: sms_mysql
    image: mysql:5.7
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes: 
        - ./mysql-dump/data:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
volumes:
  mysql-dump:
