# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: make decrypt_env executable
        run: chmod +x ./.github/scripts/decrypt_env.sh

      - name: decrypt env file
        run: ./.github/scripts/decrypt_env.sh
        env:
          ENV_SECRET: ${{secrets.ENV_SECRET}}

      - name: Unit test
        run: npm test:cov
  

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz

      - name: Build project artifact
        run: npm run build --if-present

      - name: Compress artifact
        run: tar -czvf dist.tar.gz dist package.json yarn.lock

      - name: Upload artifact to remote
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist.tar.gz
